services:
  postgres:
    container_name: titan-database
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ${ENV_FILE:-.development.env}
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  main:
    container_name: titan-api
    build:
      context: .
      target: ${CONTEXT:-development}
    env_file:
      - ${ENV_FILE:-.development.env}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: always


volumes:
  postgres-data:
    driver: local